import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Home Book',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.variable} overflow-x-hidden antialiased`}>
				{children}
			</body>
		</html>
	);
}
